name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn --network-timeout 1000000000
    - run: yarn package-win
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Winx64_executable
        # A file, directory or wildcard pattern that describes what to upload
        path: release/win-unpacked
    - name: GitHub Releases
      uses: Roang-zero1/github-upload-release-artifacts-action@v2.1.0
